# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'News' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift', '5.1.1'
  pod 'RxCocoa', '5.1.1'

  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'SwiftyJSON'
  pod 'lottie-ios'
#  pod 'SnapKit'

  pod 'SVProgressHUD'
  pod 'MJRefresh'
  pod 'HandyJSON', '5.0.2'

  pod 'IBAnimatable', '6.1.0'
  pod 'SwiftTheme'
  pod 'SQLite.swift'
  pod 'SGPagingView'
  pod 'BMPlayer', "1.3.2"

  pod 'FDFullscreenPopGesture'
  
  # pod 'Texture'
end
